# Generated by Django 5.1.7 on 2025-04-01 19:21

import board.models
import board.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_rename_address_profile_location_profile_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default=board.models.get_default_avatar, null=True, upload_to=board.models.get_avatar_upload_path, validators=[board.validators.validate_avatar_image]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[board.validators.validate_phone_number]),
        ),
    ]
